- name: Deploy kubernetes
  hosts: server
  gather_facts: True
  become: true
  tasks:
  - git:
      repo: https://github.com/metanitesh/metanitesh-CI.CD.Jenkins.Ansible.Docker.K8s.git
      dest: /home/ubuntu
      version: green-deployment
  
  - name: deploy a cluster
    shell:  kubectl apply -f /home/ubuntu/k8s/deployment.yml

  - name: deploy a cluster
    shell:  kubectl apply -f /home/ubuntu/k8s/service.yml

  - name: port-forward
    shell: port-forward service/simple-api 3000:3000
